# Generated by Django 4.1.10 on 2023-08-30 03:08

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0025_formulaire_utilisateurr_alter_resetlink_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulaire_utilisateurr',
            options={},
        ),
        migrations.AddField(
            model_name='formulaire_utilisateurr',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='formulaire_utilisateurr',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='formulaire_utilisateurr',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='formulaire_utilisateurr',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='formulaire_utilisateurr',
            table='formulaire_utilisateurr',
        ),
    ]
